### ISSUE TITLE
Question: SwitchIdent_Console source?

### ISSUE THREAD

**Issue by Rai** [joel16/SwitchIdent#11]
Hey @joel16 I was wondering where is the source for SwitchIdent_Console?

**Comment by joel16** [comment]
I had that deprecated in favour of the GUI version since it can show a lot more information. You can check this commit https://github.com/joel16/SwitchIdent/commit/e89d192ac966894626253075718609fcc9dd2847

**Comment by Rai** [comment]
Ahh ok. Makes sense.
