### ISSUE TITLE
In hos 15.0.0, the screen is black

### ISSUE THREAD

**Issue by lsp199308** [joel16/SwitchIdent#17]

**Comment by joel16** [comment]
Hey sorry, I've been busy moving out and stuff for the past couple months. I'll take a stab at this this weekend and try to push out a hotfix if its completely broken.

**Comment by proferabg** [comment]
Try commenting out wlaninfInitialize() and see if that solves your issue. If it is, that is the same issue that broke the EdiZon Overlay because the wlan:inf service doesn't exist anymore in HOS 15.0.0

**Comment by joel16** [comment]
> Try commenting out wlaninfInitialize() and see if that solves your issue. If it is, that is the same issue that broke the EdiZon Overlay because the wlan:inf service doesn't exist anymore in HOS 15.0.0

Interesting, will try it later this evening or in the weekend, thank you!

**Comment by AngelofWoe** [comment]
I know it's been months, but I commented out the mentioned lines, re-compiled, and it works.

This commit didn't seem to fix it:
dd77c6e53a0825ce96cfa55af9aaa24261e129c7

**Comment by joel16** [comment]
SwitchIdent v0.4.0 + works on the latest firmware so will close this.
