### ISSUE TITLE
Language not Identified

### ISSUE THREAD

**Issue by NorthHopper** [joel16/SwitchIdent#2]
SwitchIdent doesn't display any language, it is just blank.

**Comment by joel16** [comment]
Yeah I will fix this later, are you available for testing? maybe I can send you builds via discord or something.

**Comment by NorthHopper** [comment]
I am available for testing, how should I send you my discord?

**Comment by joel16** [comment]
Add me or, if you're in the reswitched discord ping me: Joel16#3068

**Comment by SegFault42** [comment]
Hello @joel16,

Are you using yuzu emu for testing ?

**Comment by joel16** [comment]
It won't work on yuzu anymore due to the services required. It will immediately crash, I'm just trusting my instincts at this point :p (Waiting for my switch to arrive next week)

**Comment by SegFault42** [comment]
Ok i have the same issue ^^.

**Comment by NorthHopper** [comment]
Sorry for the later reply as I've been busy today, but I will add you on Discord.
