### ISSUE TITLE
Ident does not gather all data on 5.1 FW

### ISSUE THREAD

**Issue by GhostlyCrowd** [joel16/SwitchIdent#4]
Title

**Comment by joel16** [comment]
Could you provide more info? what isn't it gathering?

**Comment by GhostlyCrowd** [comment]
Kernel, Firmware ver Hardware and Serial were failing, last I tried the GUI version.  

However i just opened the terminal version and it worked, went back to the GUI version and now it works too. Not sure what to make of it.   No idea what happened.

**Comment by joel16** [comment]
Are you using layerd FS or something out of the ordinary than just homebrew launcher?

**Comment by GhostlyCrowd** [comment]
Just bog standard HB launcher and hekate.  I noticed this when i first
updated to 5.1, tried again later still the same. Assumed it was the new
FW. Just got thinking today i should really report the issue since no one
else had and low and behold it works so i have not a clue. I'd go ahead and
close if it happens again ill make note of the order of operations it
happen in.
