### ISSUE TITLE
Battery voltage state?

### ISSUE THREAD

**Issue by maciak** [joel16/SwitchIdent#5]
Hi,
For me it shows max77620_sd3 as a battery voltage state. I believe it's not correct. I'm using version compiled by me from new commit 816ef0a.

**Comment by joel16** [comment]
Hmm I'm not sure but I'm using the data from switchbrew: https://switchbrew.org/wiki/PCV_services

What makes you think it isn't correct?

**Comment by maciak** [comment]
Well I just thought that battery voltage state should show astuall state preferably in mV and not the name of the chip.

**Comment by joel16** [comment]
That doesn't return the actual voltage.

**Comment by maciak** [comment]
Than you probably should change the name as it's a bit confusing :)

**Comment by joel16** [comment]
Oh right, that's why it's displayed as "Voltage **state**", if I was talking about actual voltage I would've just made it display "Voltage:"

**Comment by maciak** [comment]
that's fair enough :)
