### ISSUE TITLE
Input not working on FW 9.0.0 or higher

### ISSUE THREAD

**Issue by EnterpriseFreak** [joel16/SwitchIdent#9]
9.0.0 changed HID related stuff which requires homebrew to be recompiled with the newest libnx so that controller inputs work again.

**Comment by joel16** [comment]
I need to clean up some things before release. I may get around to it this weekend.

**Comment by raytan1807** [comment]
Hi, not sure whether my issue related to this or not but I am using the bleeding edge built and the GUI doesn't seem to react to my D-pad and touch screen and it stuck on the main page. I using FW 10.0.2 with AMS 0.14.1. Thanks.

**Comment by joel16** [comment]
Yes it's the same reason. It hasn't been compiled with the latest toolchain.

**Comment by joel16** [comment]
Should be fixed now with v0.3.
